##### load config #####

configfile: "config.yml"
workdir: "/Iris_test/ALL_reannotation/"
include: "rules/common.smk"
insert_df_path = "ALL_reannotation_path_bulid.txt"
insert_df = pd.read_csv(insert_df_path, sep="\t", names=["ins_id", "path", "ins_loc_hg38"])
insert_df.set_index("ins_id", inplace=True)

## step 1
get_valid_sv(insert_df, config["file"]["valid_sv"])
get_valid_repeatmasker(insert_df, config["file"]["valid_repeat"])
## step 2
sv_ls = pd.read_csv(config["file"]["valid_sv"], names=["id"])["id"].tolist()
repeat_ls = pd.read_csv(config["file"]["valid_repeat"], names=["id"])["id"].tolist()
ref_file = "/NAS/wg_fzt/OSCC1/data/ref/hg38_mainChr.fa"
ref_records = SeqIO.parse(ref_file, "fasta")
ref_records_dict = SeqIO.to_dict(ref_records)
ref_length = {}
#for seq_record in ref_records:
#    ref_length[str(seq_record.id)] = len(seq_record)

##### resources setting ######
core_num = 4
memory_assign = 20

##### target rules #####

rule all:
    input:
        config["file"]["final_summary"]


include: "rules/extract.smk"
include: "rules/needle.smk"
include: "rules/trf_pattern.smk"
include: "rules/summary.smk"
include: "rules/region.smk"
